<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<RootNamespace>FSH.Accounting.Api</RootNamespace>
		<AssemblyName>FSH.Accounting.Api</AssemblyName>
		<IsPackable>false</IsPackable>

		<!-- Container configuration -->
		<ContainerPort>8080</ContainerPort>
		<ContainerUser>root</ContainerUser>
		<ContainerRepository>fsh-basic-api</ContainerRepository>
    	<PublishProfile>DefaultContainer</PublishProfile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Mediator.Abstractions" />
		<PackageReference Include="Mediator.SourceGenerator">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Web\Web.csproj" />
    <ProjectReference Include="..\..\..\Modules\Auditing\Module.Auditing.Contracts\Module.Auditing.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Modules\Auditing\Module.Auditing\Module.Auditing.csproj" />
    <ProjectReference Include="..\..\..\Modules\Identity\Module.Identity\Module.Identity.csproj" />
    <ProjectReference Include="..\..\..\Modules\Multitenancy\Module.Multitenancy\Module.Multitenancy.csproj" />
    <ProjectReference Include="..\..\..\Modules\Todos\Module.Todos.Contracts\Module.Todos.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Modules\Todos\Module.Todos\Module.Todos.csproj" />
    <ProjectReference Include="..\Migrations.PostgreSQL\Accounting.Migrations.PostgreSQL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\uploads\" />
  </ItemGroup>

</Project>
