using FSH.Playground.Blazor.ApiClient;

namespace FSH.Playground.Blazor.Services;

/// <summary>
/// Extensions for TodoClient to add DeleteAsync method
/// (not generated by NSwag due to OpenAPI discovery limitation)
/// </summary>
internal static class TodoClientExtensions
{
    public static async System.Threading.Tasks.Task ListsDeleteAsync(
        this ITodoClient client,
        System.Guid id,
        System.Threading.CancellationToken cancellationToken = default)
    {
        if (id == Guid.Empty)
            throw new System.ArgumentException("id cannot be empty", nameof(id));

        // Cast to TodoClient to access the protected HttpClient field via reflection
        if (client is not TodoClient todoClient)
            throw new InvalidOperationException("TodoClient instance required");

        var httpClient = todoClient.GetType().GetProperty("HttpClient", 
            System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)
            ?.GetValue(todoClient) as HttpClient
            ?? throw new InvalidOperationException("Could not access HttpClient");

        using var request = new HttpRequestMessage(HttpMethod.Delete, $"api/v1/todo/lists/{id}");
        var response = await httpClient.SendAsync(request, cancellationToken).ConfigureAwait(false);
        
        if (response.StatusCode == System.Net.HttpStatusCode.NotFound)
            throw new ApiException("Not Found", 404, "", new Dictionary<string, System.Collections.Generic.IEnumerable<string>>(), null);
        
        response.EnsureSuccessStatusCode();
    }
}
