<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>Ai.Tests</RootNamespace>
		<AssemblyName>Ai.Tests</AssemblyName>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<NoWarn>$(NoWarn);CA1515;CA1861;CA1707</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoFixture" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="NSubstitute" />
		<PackageReference Include="Shouldly" />
		<PackageReference Include="xunit" />
		<PackageReference Include="xunit.runner.visualstudio" />
		<PackageReference Include="coverlet.collector" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Modules\Ai\Modules.Ai\Modules.Ai.csproj" />
		<ProjectReference Include="..\..\Modules\Ai\Modules.Ai.Contracts\Modules.Ai.Contracts.csproj" />
	</ItemGroup>

</Project>
