<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Accounting.Domain\Accounting.Domain.csproj" />
      <ProjectReference Include="..\..\..\..\Shared\Shared.csproj" />
      <ProjectReference Include="..\Accounting.Application\Accounting.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="QuestPDF" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.AspNetCore.Routing">
        <HintPath>..\..\..\..\..\..\..\..\..\usr\local\share\dotnet\shared\Microsoft.AspNetCore.App\9.0.2\Microsoft.AspNetCore.Routing.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Persistence\Configurations\CostingMethodConfiguration.cs" />
    </ItemGroup>

</Project>
