<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>FSH.Modules.Accounting.Contracts</RootNamespace>
		<AssemblyName>FSH.Modules.Accounting.Contracts</AssemblyName>
		<PackageId>FullStackHero.Modules.Accounting.Contracts</PackageId>
		<NoWarn>$(NoWarn);CA1002;S1135</NoWarn>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\BuildingBlocks\Core\Core.csproj" />
	</ItemGroup>

</Project>
