<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>FSH.Modules.Microfinance.Contracts</RootNamespace>
		<AssemblyName>FSH.Modules.Microfinance.Contracts</AssemblyName>
		<PackageId>FullStackHero.Modules.Microfinance.Contracts</PackageId>
		<NoWarn>$(NoWarn);CA1711</NoWarn>
	</PropertyGroup>

</Project>
