<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>FSH.Module.Todos</RootNamespace>
		<AssemblyName>FSH.Module.Todos</AssemblyName>
		<PackageId>FullStackHero.Modules.Todo</PackageId>
		<NoWarn>$(NoWarn);CA1031;CA1812;CA1859;S3267;S1135</NoWarn>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\BuildingBlocks\Persistence\Persistence.csproj" />
	  <ProjectReference Include="..\..\..\BuildingBlocks\Web\Web.csproj" />
	  <ProjectReference Include="..\..\..\BuildingBlocks\Eventing\Eventing.csproj" />
	  <ProjectReference Include="..\Module.Todos.Contracts\Module.Todos.Contracts.csproj" />
	</ItemGroup>

</Project>
